chore: update dependencies to remove vulnerabilities
silvermine/videojs-quality-selector pull request #73
Opened 2021-05-11 21:18 UTC by jimjenkins5

Note: This PR does not fix a vulnerability in `grunt-sass-lint`. That will be addressed by replacing sass-lint with stylelint in a future PR.

2021-05-12 14:40 UTC, jthomerson commented on package.json
> +    "grunt": "^1.4.0",
caret slipped in here

2021-05-12 14:46 UTC, jimjenkins5 commented on package.json
> +    "grunt": "^1.4.0",
Erg! `npm audit` needs a `--dont-give-me-fuzzy-dependencies` flag.

Fixed.

2021-05-13 18:44 UTC, yokuze requested changes
Looking good @jimjenkins5 - just a couple little things.

2021-05-13 18:44 UTC, yokuze commented on .editorconfig
> +[*]
Can we do what you did for `.editorconfig` in this PR: https://github.com/silvermine/videojs-chromecast/pull/95/files#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5b  ?

2021-05-13 18:44 UTC, yokuze commented on .nvmrc
> +v12.22.1
I don't think we normally put the `v` in front of the version number.

2021-05-13 18:48 UTC, jimjenkins5 commented on .nvmrc
> +v12.22.1
Oh. I just did `node -v > .nvmrc`. I guess I can take it out. All the similar PRs I just did have the v... 🤷‍♂️

2021-05-13 19:02 UTC, jimjenkins5 commented on .editorconfig
> +[*]
👍

2021-05-13 19:02 UTC, jimjenkins5 commented
Back to you @yokuze

2021-05-13 21:20 UTC, yokuze approved these changes
This looks good. @jthomerson after this is merged we will need a new NPM package published. Thanks!

2021-05-14 02:29 UTC, jthomerson approved these changes

2021-05-14 02:30 UTC, merged

2021-05-14 02:32 UTC, jthomerson commented
Published in + @silvermine/videojs-quality-selector@1.2.5

CC @yokuze @jimjenkins5