docs: Remove data-setup property to prevent double initialization (#70)
silvermine/videojs-quality-selector pull request #83
Opened 2022-02-22 00:26 UTC by izkmdz

Using the `data-setup` attribute in the video component will automatically initialize the player with the options provided. However, if the player is also initialized in our code using the `videojs('my-player')` function, this can sometimes cause the issue described in #70, where the quality selector is unable to change sources. 

These changes remove the `data-setup` attribute from the documentation and demo to prevent this from occuring.

2022-02-23 16:55 UTC, yokuze requested changes

2022-02-23 16:55 UTC, yokuze commented on README.md
> +videojs("video_1", {}, function() {
Nit: can we use single quotes here to match our standards?

2022-02-24 14:50 UTC, yokuze requested changes

2022-02-24 14:50 UTC, yokuze commented on README.md
> +   player.controlBar.addChild('QualitySelector');
Sorry - could you add the newline between the `var` and this line, to match the code in the demo page?

2022-02-28 18:28 UTC, izkmdz commented on README.md
> +   player.controlBar.addChild('QualitySelector');
Fixed. Thanks! 👍

2022-04-04 12:54 UTC, yokuze approved these changes

2022-04-04 12:54 UTC, merged