Use ES6 classes instead of videojs.extend
silvermine/videojs-quality-selector pull request #93
Opened 2023-01-29 14:23 UTC by absidue

video.js 8 removes the `videojs.extend` function and recommends using native ES6 classes. Recent versions of video.js already spit out deprecation warnings when that function is used.
https://videojs.com/guides/videojs-7-to-8/#videojsextend

2023-03-22 00:12 UTC, yokuze requested changes
@absidue Thank you for the PR. Overall it looks good, we just need to maintain backward compatibility with browsers that do not support ES6+ class syntax. Similar work is being done in https://github.com/silvermine/videojs-airplay/pull/44/files where the author added Babelify to transpile the class syntax to ES5. Could you use that PR as a guide to do the same?

The other changes in that PR, such as the tests, are nice to have but not necessary if you're not inclined to include them.

2023-03-27 08:38 UTC, absidue commented
@yokuze looks like babelify was already introduced in https://github.com/silvermine/videojs-quality-selector/pull/86.

2023-05-26 20:18 UTC, andreas-venturini commented
@yokuze does this address your concerns re backwards compatibility?

2023-06-23 22:01 UTC, gsimko commented
Can you please also update the icon to \f114 as done in pr #99? With videojs 8 it is showing the incorrect "download file" icon instead of the gears.

2023-06-28 17:41 UTC, eugecodes commented
Thanks so much because this truly fixed the issue I had of incompatibility between video.js last version and this plugin which made it unusable.

2023-06-28 17:48 UTC, absidue commented
@gsimko Changing that icon to a video.js 8 specific one, will probably break it for video.js 7 and below.

2023-07-18 09:31 UTC, cbarburescu commented
Are there any updates on this? Thank you

2023-07-21 13:27 UTC, gsimko commented
Just to clarify, if the icon change needs further discussion, we should get this PR submitted without touching that part. Users can circumvent the icon problem, but not the breaking problem that this PR fixes.

2023-07-22 20:31 UTC, andreas-venturini commented
My suggestion would be to get this PR merged and released, then open a follow-up PR that addresses the breaking change introduced by video-js with regard to the icon (this could then be a new major release that marks dropping Video.js 7 support as breaking change)

Matt is probably busy so maybe @pbredenberg or @onebytegone can decide whether this PR is good to go as is or needs additional work

2023-07-31 12:52 UTC, josipRajkovicFlowout commented
Hello,
thanks for all the work. Are there any updates to this? Any approximation as to when this might be merged?

2023-08-01 14:24 UTC, yokuze approved these changes

2023-08-01 14:25 UTC, merged

2023-08-01 14:25 UTC, yokuze commented
Thank you @absidue!

2023-09-06 08:41 UTC, cokuna-pavelkosolapov commented
Hello, @yokuze can you please make an update by npm?

2023-09-19 15:26 UTC, fguillen commented
In which version is this merged? CDNs are serving v1.1.2 :?

2023-10-05 15:08 UTC, r152a commented
no changes in https://www.npmjs.com/package/@silvermine/videojs-quality-selector

2023-10-16 18:51 UTC, alemosa commented
Hello, what's the status on this? On video.js 8.6.0 it's still showing the videojs.extend is not a function problem.
Thanks

2023-10-26 07:15 UTC, valentin-anamorphik commented
Hi, 

Is the problem resolved?

2023-10-26 07:51 UTC, r152a commented
> Hi,
> 
> Is the problem resolved?

No. If I install via npm, the problem is not solved. That's why I can't upgrade to the new version of videojs.

2023-11-14 14:34 UTC, andreas-venturini commented
As a workaround until a new release is available on npm: Yarn can fetch packages [from a git repository](https://yarnpkg.com/protocol/git). Include the following line in your project's `package.json`:

```json
"videojs-quality-selector": "https://github.com/silvermine/videojs-quality-selector/archive/d16842b1acb16cb25f12404ce56d8577b1c61a8d.tar.gz",
```

Then overwrite the wrong font icon (download icon) to restore the cog icon again (as per https://github.com/silvermine/videojs-quality-selector/pull/93#issuecomment-1605032384):

```scss
.vjs-quality-selector {
  .vjs-icon-placeholder::before {
    content: "\f114";
  }
}
```

2023-11-14 15:08 UTC, r152a commented
@yokuze When should we expect a new release in npm?